### ISSUE TITLE
API should support a flag to disable marketplace and autoupdates

### ISSUE THREAD

**Issue by WoLfulus** [directus/docker#1]
As we are working with an immutable infrastructure, images shouldn't change after they are built.

I suggest adding an environment variable like `DISABLE_MARKETPLACE` and `DISABLE_AUTOUPDATE` so these features won't make any changes to the filesystem and/or code inside the image.

The Docker images should still allow auto-updates and marketplace plugin installations because some people will want to mount those folders as volumes, but they should be explicitly enabled in this case.

API should also pass this information to the APP so we can disable the interface as well.

**Comment by rijkvanzanten** [comment]
> so these features won't make any changes to the filesystem and/or code inside the image.

What about image uploads / error log files?

**Comment by WoLfulus** [comment]
We should guide the end user into using something like minio/s3 for storage and/or mounting the data folder (uploads) into a volume, which is pretty normal on docker environments

**Comment by stickgrinder** [comment]
I guess volumes are the way to go for a first iteration. They are also the go-to choice in Kubernetes envs that are becoming the de facto standard for container orchestration today.

**Comment by WoLfulus** [comment]
To be reviewed in the future as we don't have those feature in place right now.
