### ISSUE TITLE
Multitenancy using ENVARs

### ISSUE THREAD

**Issue by zfalen** [directus/docker#100]
Howdy! I am playing with v8+ after using v7 for awhile. 

Obviously, API and App are bundled together now. I am curious how, if it's possible at all, to enable one Directus container to access multiple databases. In our case, this would be multiple DBaaS instances, some with more than one Directus database in them, some with just one. 

In v7, we could spin up an API container for each one and assign envars that pointed to the database location w/credentials. Then, using a single _App_ container we could use the following envars to access any of these APIs from one place:

```
    DIRECTUS_ALLOW_OTHER_API: "true"  // (allow manual entry)

    DIRECTUS_APP_TITLE: "Some Cool App"
    DIRECTUS_APP_URL: "http://localhost:8080/_/"
 
    DIRECTUS_APP2_TITLE: "Another Neat App"
    DIRECTUS_APP2_URL: "http://someOtherHostedURL/_/"
```

I don't see an equivalent for v8+ documented anywhere, but the docs indicate it may be possible using a config file _(which I assume we would volume in?)._ https://docs.directus.io/advanced/api/configuration.html#project-config-files

@WoLfulus - is this advisable in v8+, or should we move to a world where each app has its own App? If possible, is there a good example somewhere with the new envars, or with a config file that enables this functionality?

**Comment by benhaynes** [comment]
One install instance of Directus can manage multiple databases (projects), some being public, and others private. This should give you the flexibility you need:

https://docs.directus.io/guides/projects.html

**Comment by WoLfulus** [comment]
On v8, there's an endpoint that returns the installed projects, so there's no need to explicitly configure them. 

But if you want to enable multi tenancy in docker, you're better disabling the environment variable setup and mounting project files instead. We don't have a proper way to setup multi project setups through environment variables right now.

I'll think a better way to handle this once we have our rewrite in place.

**Comment by zfalen** [comment]
Cool. I rather liked the `APP1`, `APP2`, `APP3` environment variable approach. It was really simple to just restart a container and get access to a new database. Although I suppose that raises the question of the install command needing to loop over all your "projects" and install them if they haven't been already, which was easier when a single API was linked to one DB. 

Anyways, it would seem the "projects" approach will accomplish what we need and it looks like I can volume over the appropriate config files. **I am not sure how to manage installs in this case however. Would running the "installer" in the next paragraph seed an empty DB? Or does it need to be run manually before the new DB table is created?** 

Or, I can use the installer @benhaynes referenced. However, I'm running into this error when creating projects:
<img width="1659" alt="Screen Shot 2020-02-18 at 10 09 32 AM" src="https://user-images.githubusercontent.com/14879054/74760017-fb891c80-5236-11ea-8b92-664aa983f07d.png">

@WoLfulus - I can't find anything in the Docker documentation around an envar controlling this. Is there another secret one I can add to my docker-compose? 

Alternatively, we can just have a dedicated Directus install stand up next to each app that needs it which is fine. And makes doing all of this with docker-compose easier.

**Comment by WoLfulus** [comment]
You can find it here: https://docs.directus.io/docker/overview.html#disabling-environment-variables

**Comment by zfalen** [comment]
Well, yes, but I guess I was wondering if I can still use the envars from docker-compose, just add one that will turn off the error message above :)

**Comment by zfalen** [comment]
@WoLfulus - ah, I see it. In /Directus/Config/Context.php:
```
    public static function is_env()
    {
        return getenv('DIRECTUS_USE_ENV') === '1';
    }
```

And in Directus/Services/ProjectService.php:
```
    if (Context::is_env()) {
        throw new ForbiddenException('Project creation is disabled under environment variables.');
    }
```

My assumption is that disabling `DIRECTUS_USE_ENV` also disables all my other envars, so I answered my own question. And we will have to pass on that for now. Will use single installs for each app instead. 🙂

**Comment by zfalen** [comment]
@WoLfulus - where can I find an example with a complete `config.php` file to reference in case I go down the no envars path?

**Comment by WoLfulus** [comment]
the wizard should generate it, but here's one https://github.com/directus/api/blob/master/config/_example.php

**Comment by zfalen** [comment]
You da man. Thx.

**Comment by WoLfulus** [comment]
just make sure the volume has the right permissions if you're using mounts (www-data)

closing this one
