### ISSUE TITLE
Change the size of uploaded file

### ISSUE THREAD

**Issue by egel** [directus/docker#103]
### Expected behavior
As a developer

I want to be able to change `upload_max_filesize` from apache config

so I can change how large files I want to upload.

### Actual behavior
In current version v8.5.5-apache there is no option to easily customize the maximal size of uploaded files.

### Acceptance

- [ ] developer is able to customize `upload_max_filesize` in development and production environment

### Suggested solution
Maybe add the possibility to override php.ini-production and development while running a docker image (using dynamic volumes).

### Additional Information

*   Environment(s): 
*   Browser(s): -
*   OS(es): OSX / docker 19.03 / docker-compose 1.25
*   Occurs in the branch (tag or commit): 6daaa5f8fde457df6bba5550955edc2614f64594
*   Depends on issue(s): -
*   Related to issue(s): -

**Comment by apiraino** [comment]
@egel it's already possible what you're asking.

You can expose the `directus-custom.ini` (which I believe it's there for this purpose) on the host filesystem:
```
- volumes:
    ...
    ./data/php.ini:/usr/local/etc/php/conf.d/directus-custom.ini
```

and there you can override the PHP config editing the `./data/php.ini` file

Hope this helps!

**Comment by egel** [comment]
Thank you @apiraino. 🙌  I couldn't find that after the first quick search and skim through all issues. I think I missed that then. I'll try this soon and give feedback about it.

PS. Is this mentioned somewhere in documentation? If not, would be great to add it there.

**Comment by egel** [comment]
Yes, this works perfectly fine. Thank you @apiraino for your help! 🙌

**Comment by apiraino** [comment]
> PS. Is this mentioned somewhere in documentation? If not, would be great to add it there.

I see a [reference here](https://docs.directus.io/getting-started/troubleshooting.html#frequently-asked-questions), the rest is Docker knowledge you can get [from their documentation](https://docs.docker.com/compose/compose-file/#volumes).
