### ISSUE TITLE
question/doc: what values should DIRECTUS_AUTH_SECRETKEY, DIRECTUS_AUTH_PUBLICKEY have?

### ISSUE THREAD

**Issue by shaunc** [directus/docker#115]
The documentation says that these should be random strings. Usually a public key has a specific relationship to a private key. How are these used? Are they related to bearer tokens on the API? How does one generate tokens to match these? In general, how auth works is poorly explained in the documentation.

**Comment by WoLfulus** [comment]
it can be literally anything, it just shouldn't be the same for security reasons (i enforced this on docker images but i think api still allows it to have the same value for both)

if i'm not mistaken, the secret key is used as a jwt password for HS256 algo, and public is a key that goes into the jwt payload
