### ISSUE TITLE
Docker use of /run/secrets 

### ISSUE THREAD

**Issue by MarcHagen** [directus/docker#121]
In cluster environments its common practice to use secret files instead of environment keys for passwords.

At the moment there is no such implementation for Directus docker, but i would really like to have it so i can use existing secrets to relay information.

**Comment by WoLfulus** [comment]
We'll be adding this on v9/v10

**Comment by MarcHagen** [comment]
Yeah, didn’t know if was “allowed”/desired to make issues here. 
That’s why I also made a discussion on the main project.
