### ISSUE TITLE
Docker project documentation

### ISSUE THREAD

**Issue by stickgrinder** [directus/docker#15]
Following a discussion on Slack, I'd like to help with documentation, starting out with the following:

* available repository and their roles
* how dockerhub images are built and which availability the community should expect
* architecture of the docker images (and possible reasons behind architectural choices)
* contributions guidelines
* FAQ/Q&A

I'm available to collect raw information from relevant people (mostly @WoLfulus I guess) and work out some human-readable contributions.

**Comment by benhaynes** [comment]
Best next step would be a Pull Request to the [Docs repo](https://github.com/directus/docs). I think all the Docker info should go within a `Docker` guide, so we can duplicate the structure of a page like this: 

https://github.com/directus/docs/blob/master/guides/roles.md

As soon as we have a basic structure I'd say let's merge it in so it's on our Docs site (even if it's bare bones). Then we can extend, polish, and adjust things from there!

**Comment by stickgrinder** [comment]
Very good, it would be great to have all in one place! Forking... ;)

**Comment by WoLfulus** [comment]
I'm working on this together with #16 #40 and #82

**Comment by WoLfulus** [comment]
I think most of these are now solved by https://github.com/directus/docs/pull/258
