### ISSUE TITLE
Add descriptions to DockerHub repos

### ISSUE THREAD

**Issue by benhaynes** [directus/docker#16]
Hey @WoLfulus — let's get some descriptions of what the `app`, `api`, and `builder` repos on our DockerHub are.

**Comment by mrleblanc101** [comment]
It's been 6 months, any news on when the docker documentation will be published ?

**Comment by benhaynes** [comment]
We're just now wrapping up the new Docker today! We're also working on the Docs now...

**Comment by mrleblanc101** [comment]
Documentation on how to docker-compose, volume management and maybe how to update Directus manually if the docked get out of sync again would be very nice for Docker newbie like me

**Comment by srhise** [comment]
Thanks for working on the docs. I am trying very hard to understand how to run these docker images so I can work locally then deploy to AWS but I've got stuck several times on setup and I'm not quite sure what I should be doing to get Directus 7 working on Docker.

**Comment by WoLfulus** [comment]
Seems like it's not that clear yet from the readme just yet, but these images are not mean't to be run, they should be extended. None of the images contains directus code just yet.

I'll will provide `dist` images soon, and you'll be able to build custom ones using base images.

**Comment by srhise** [comment]
Ok, thanks that makes sense. The old images seemed like they were ready to run like you said. I'd be glad to help write some instructions once the images are up to help - if I can figure it out. This project is awesome! We run everything on AWS ECS so docker is a must with the way we do devops.

**Comment by WoLfulus** [comment]
I'm focused on ops myself, so I'm trying to get things right to make ops easy. :)

**Comment by WoLfulus** [comment]
I'm working on this together with #15 #40 and #82

**Comment by WoLfulus** [comment]
docker hub is getting updated automatically now.
