### ISSUE TITLE
docker-compose up does not  work as expected

### ISSUE THREAD

**Issue by dev7ch** [directus/docker#18]
`ERROR: manifest for wolfulus/directus-api:latest-alpha not found` 

Is there sth not updated or i am wrong?

`cd projects/ && docker-compose up`

**Comment by WoLfulus** [comment]
That file shouldn't have been commited. My bad.

Use examples folder instead.

**Comment by dev7ch** [comment]
ok thank you.

inside `local/` or `examples/` it is working fine

**Comment by WoLfulus** [comment]
Awesome! 😄
