### ISSUE TITLE
API plugins should be installed via CLI commands

### ISSUE THREAD

**Issue by WoLfulus** [directus/docker#2]
Following the idea of immutable infrastructures, we should allow plugin installations from marketplace via CLI commands, which allows us to build custom images based on the official ones and extend its features installing additional plugins.

This should work even if disable flags are set (https://github.com/directus/docker/issues/1)

For example, the following will build an image with three plugins installed.

```
FROM directus/directus:stable
RUN directus plugin install <plugin1>@1.0.3
RUN directus plugin install <plugin2>@2.0.0
RUN directus plugin install <plugin3>@latest
```

We can study how `npm` or `pip` works for installing packages.

**Comment by benhaynes** [comment]
This should be possible, right @WellingGuzman ?

**Comment by stickgrinder** [comment]
Sounds like using a composer-like strategy for plugins may also do. Declaring plugins and updates in a file and issuing a single build would also allow to run custom builds starting from stable image without adding layers for each plugin or update (can still be done with a single RUN and chained commands).

In addition, having them in a declarative format allows for a single volume mount in local development.
Am I totally off road?

**Comment by WoLfulus** [comment]
Thats awesome. I haven't thought about the composer-like strategy.

Also, what you mean with declarative format? Having a single folder where extensions are stored?

**Comment by WoLfulus** [comment]
To be reviewed in the future.
