### ISSUE TITLE
Add volumes by default for persistent data

### ISSUE THREAD

**Issue by PostPollux** [directus/docker#21]
I think it would be great if there were volumes added to the docker-compose files by default. I could do it myself, but I actually don't really know which paths I should map to a volume. Any hints?

I guess for the mysql container it's: /var/lib/mysql

But which paths are supposed to be used for "api" or "app" if any?

**Comment by WoLfulus** [comment]
Cool! 

I'll add more examples that shows the paths.

**Comment by PostPollux** [comment]
Ok, now that Directus finally works on my side I guess there have to be no other volumes! Am I right on this one?

The app seems to be only the frontend part so I have a ui to work with the api and database. No reason here to make something persistent... 

The API container seems to just create the api based on the database data. So there seems to be no need for persistent data as well.
In the api documentation I read "The Directus API is a quick and easy way to add a RESTful API layer to a new or existing SQL database. It perfectly mirrors the database architecture which allows for flexible content modeling and dynamic endpoints even when changing the schema or data directly."

And it seems to be true. If I kill all containers by "docker-compose down" and bring new ones up again, everything works as it should by just preserving the volume of the database. So I think that's enough.
Am I missing something?

If not, maybe this could be mentioned somewhere that this is the only volume needed. At least for me it was not obvious at the beginning.

**Comment by WoLfulus** [comment]
For `app`, yes, you're right - no need.

For `api` you should map volumes for file uploads (but for a cloud-native deployment you should use s3 instead)

**Comment by pdsm** [comment]
> For `app`, yes, you're right - no need.
> 
> For `api` you should map volumes for file uploads (but for a cloud-native deployment you should use a s3-compatible server instead)

I am trying to map volumes for file uploads with /var/lib/api and its not working, the path its wrong?

**Comment by PostPollux** [comment]
@pdsm 
I already found the right path. It has to be: /var/www/html/public/uploads

**Comment by pdsm** [comment]
/var/www/html/public/uploads is not working, can you share your docker file?

**Comment by PostPollux** [comment]
For me this path works. I'm not using AWS S3 storage. It's just on my server as well.



Here is my docker-compose file for the API. I'm using my own directus api image here, but it is exactly the same as the original with the difference, that I can set max upload sizes via an environment variable. I think I will make a pullrequest for that max upload size setting the next days so this can be add to the official dockerfile if the community and the developers find it useful :

https://pastebin.com/CKU5h1Zq


And here is the corresponding .env file:

https://pastebin.com/Lkw9yLAm


If you want this setup to work you have to also run the jwilder/nginx-proxy plus its ssl companion container, or you publish the ports with "ports" istead of just exposing them.

**Comment by pdsm** [comment]
> For me this path works. I'm not using AWS S3 storage. It's just on my server as well.
> 
> Here is my docker-compose file for the API. I'm using my own directus api image here, but it is exactly the same as the original with the difference, that I can set max upload sizes via an environment variable. I think I will make a pullrequest for that max upload size setting the next days so this can be add to the official dockerfile if the community and the developers find it useful :
> 
> https://pastebin.com/CKU5h1Zq
> 
> And here is the corresponding .env file:
> 
> https://pastebin.com/Lkw9yLAm
> 
> If you want this setup to work you have to also run the jwilder/nginx-proxy plus its ssl companion container, or you publish the ports with "ports" istead of just exposing them.

I am trying to deploy this on kubernetes on gcp, using a PersistentVolume:

**mountPath: /var/www/html/public/uploads**

But the data is not saved after an implementation, some idea of ​​what might be happening?

**Comment by PostPollux** [comment]
No sorry, I have no idea. Never used gcp and kubernetes so far.

**Comment by WoLfulus** [comment]
@pdsm 

Are you mapping `api` ou `app` container? Just to make sure.

**Comment by WoLfulus** [comment]
This should be solved in
https://github.com/directus/docker/commit/9dcff9f5e0b25ba89116f6e2f15246c98cdbfe3c

I've added VOLUME instructions and folder seed to the image.
