### ISSUE TITLE
Why exposing database port

### ISSUE THREAD

**Issue by tvld** [directus/docker#24]
Any reason you are exposing [3306](https://github.com/directus/docker/blob/master/examples/single-api/docker-compose.yml) for the database? It is not needed other than by the ``api`` container, is it ?  

So, would it not be better to use  [depends_on](https://docs.docker.com/compose/compose-file/#depends_on) ?

**Comment by WoLfulus** [comment]
It's exposed just for local access. It's really not needed.

I'll remove it on the next patches!

;)

**Comment by tvld** [comment]
ok, clear, thanks. Assume you got it covered somewhere else, so will close this ticket.

I suppose local access could mean PhpMyAdmin or such? ... But we can run admin tools in containers as well in sake of consistency.))

**Comment by WoLfulus** [comment]
I was using TeamSQL to debug some startup scripts that interacts with the database, and I left the port on the compose file.

I could add adminer/phpmyadmin in some examples later too
