### ISSUE TITLE
 Form error is not shown in the dashboard

### ISSUE THREAD

**Issue by pdsm** [directus/docker#25]
Hello,

I am adding data in a new collection (where there are errors) but they are not showing in the form. Neither the red field nor any message.

In the image you can see that there is an error looking for resources, also is looking in the API URL (I do not know if this is right)

![image](https://user-images.githubusercontent.com/7040976/52601330-2929d180-2e3d-11e9-8330-be02be9803e1.png)

PS: using **Directus 7** in docker with the latest images.

Thanks for the help

**Comment by PostPollux** [comment]
same here

**Comment by rijkvanzanten** [comment]
It's rendering a notification on a non-docker install for me

<img width="466" alt="image" src="https://user-images.githubusercontent.com/9141017/52665808-8a53b280-2eda-11e9-84d9-652a28b8286b.png">

**Comment by rijkvanzanten** [comment]
I can't think of any reason why the Docker install would handle errors any differently 🤔

**Comment by PostPollux** [comment]
On my side it's finally working with app version 7.0.18!
Thanks for fixing!

**Comment by pdsm** [comment]
Its working!

Thanks!

**Comment by benhaynes** [comment]
Awesome! I'll assume this one is closed then. If someone else is experiencing this issue let us know!
