### ISSUE TITLE
API should allow auto-installation of the database

### ISSUE THREAD

**Issue by WoLfulus** [directus/docker#3]
When auto-provisioning infrastructure, we can allow some kind of auto-installation of the database. 

For example, if a system is built around Directus, we might want to provision infrastructure for tenants automatically (via k8s or any other orchestrator), the image in this case should be able to detect new installations and create all the necessary directus tables.

I did some tests here for my own specific cases, but we need to discuss this more

https://github.com/WoLfulus/directus-builder/blob/master/projects/api/bootstrap.php

I thought about describing the database schema with a `.yml` to make it easier to deploy new installations, so we can just pass the schema via secrets/configs and the image will handle the creation of the database itself.

**Comment by rijkvanzanten** [comment]
The database schema is being installed using the migration files (and seeders) in https://github.com/directus/api/tree/master/migrations. Maybe we can use that for this too?

**Comment by benhaynes** [comment]
I still like the idea of defining the schema in YAML/JSON... but for now we have the SQL/PHP migration files, so we should see if we can make those work.

**Comment by WoLfulus** [comment]
I think thats the one I'm using right now on `bootstrap.php` link I mentioned. 

For directus stuff this works well, but I'm thinking about developers that built systems around directus and wants to provision containers for tenants (they must also install their own tables)

As an alternative, I thought about something like an initialization scripts and expose some CLI commands to automate what we would normally do through `app` interface on first login

```
#!/bin/bash

directus table create <table>
directus column create <table> <column> ...
```

so that Directus will initialize the database and all the necessary metadata information

**Comment by rijkvanzanten** [comment]
@stickgrinder it also plays in with the idea of an export and import endpoint. We've been toying with the idea of having a way to import/export your current schema setup to JSON

**Comment by WoLfulus** [comment]
that would be nice, since we can configure the base instance, export the data and make the image import everything later

**Comment by stickgrinder** [comment]
I also prefer explicit declarations. But the fundamental part here is to create a _contract_ to store schema configuration in code. Importing/exporting/generation is just icing :)

**Comment by WoLfulus** [comment]
auto installation is too risky and we'll avoid it. we'd display a setup dialog specific to docker environment for database setup

**Comment by everyx** [comment]
@WoLfulus can you give some more details about use this setup dialog? so many thanks.

**Comment by everyx** [comment]
> its not implemented yet, I raised the problem with the team some days ago. you'd still need to import the schema manually

Great, thanks and happy to get that, look forward this feature pop up. :)
