### ISSUE TITLE
No collections menu item in fresh installed app (docker)

### ISSUE THREAD

**Issue by matchish** [directus/docker#32]
I've never used directus before and maybe I'm doing something wrong but I don't see collection menu item
I've used https://github.com/directus/docker/blob/master/examples/single-api/docker-compose.yml
How to create new collection?

**Comment by matchish** [comment]
![onpaste 20190228-164735](https://user-images.githubusercontent.com/818563/53575051-70bc9700-3b79-11e9-8b30-edcfe0818cfc.png)

**Comment by benhaynes** [comment]
1. Admin Settings
2. Collections and Fields
3. Add New Collection
4. Then add some fields to that collection

Then it will appear in your nav bar!
