### ISSUE TITLE
dockerhub is not updated with latest versions

### ISSUE THREAD

**Issue by ramigblv** [directus/docker#35]
Hey guys, I read somewhere that you stopped for the time being automatically updating docker containers. Do you have any ETA on when the automatic update of docker hub images will happen again?. 

Because for now the containers are outdated.

**Comment by benhaynes** [comment]
We're getting closer to a refactored Docker build flow. Any additional timeline insight @WoLfulus ?

**Comment by mvhirsch** [comment]
Any news? I'm missing `directus/api:2.0.20` and `directus/app:7.1.0`. 

Would be great if this could be updated soon!

**Comment by benhaynes** [comment]
Hey @mvhirsch — @WoLfulus is super busy at the moment, but should have time to address these issues in a week or so. Real world constraints of the open-source world! :)

**Comment by kateerogers** [comment]
@benhaynes @WoLfulus Do you know of any way that we can update the API version (it looks like there is a docker environment variable in the docker containers) manually in the docker container before the newest docker container version gets released? I would like to pull the newest API code in a docker container whenever possible. Thanks!

**Comment by eldarc** [comment]
I ended up forking this repo and pushing the latest versions to our docker hub:

https://github.com/ministryofprogramming/directus-docker
https://hub.docker.com/u/ministryofprogramming

There is also an API S3 support version which builds upon the latest API:
https://hub.docker.com/r/ministryofprogramming/directus-api-s3

**Comment by WoLfulus** [comment]
Sorry the delay and missing updates guys. I'm working on it!

@eldarc solution can be a workaround for now

Some updates?

I've been changing some stuff inside the `api` project to make it easier to configure stuff and avoid maintaining custom code inside this repository (basically making api aware of environment variables by default).

I also changed how we'll build/deliver the containers - we'll have a base container that will enable extending features and installing custom extensions

(still not done yet, but to have an idea)

```
ARG VERSION=2.0.0
FROM directus/api-apache-base:latest

// IMPLICIT ONBUILD RUNS

RUN directus-enable-extension mycustomextension
RUN composer install some-package
```

**Comment by dario30186** [comment]
Hi
any news about new docker images?
The last version for the app is 7.0.18 and it is missing a lot of bug fix.

Thank you

**Comment by benhaynes** [comment]
Hey @dario30186 — look for an update on timing here:

https://github.com/directus/docker/issues/47

**Comment by eldarc** [comment]
@dario30186 You could use these Docker images: https://hub.docker.com/u/ministryofprogramming
However, we integrate hot-fixes here which are not necessarily part of the official release.

Or you could build and push to Dockerhub your own releases: https://github.com/ministryofprogramming/directus-docker

Just put your docker username and password into `build-builder.sh`, `build-app.sh` and `build-api.sh`. And run them in that order one by one.

**Comment by WoLfulus** [comment]
see https://github.com/directus/docker/issues/54#issuecomment-528552503
