### ISSUE TITLE
S3 Support - Possible documentation addition

### ISSUE THREAD

**Issue by eldarc** [directus/docker#36]
By using just the official image it was not possible to use S3 successfully. To solve it I had to build a custom image based on this comment: https://github.com/directus/api/issues/718#issuecomment-457371997

I published it here: https://github.com/eldarc/directus-docker-s3

It would be nice to include instructions in the README on how to setup S3, if there are no plans to bundle the S3 dependency.

**Comment by mvhirsch** [comment]
@eldarc it's not in the readme, but in the official docs: https://docs.directus.io/advanced/api/configuration.html#storage

Does this help?

**Comment by mimamuh** [comment]
@mvhirsch The issue is that `aws/aws-sdk-php` is not installed on the docker image by default so it won't work.

**Comment by benhaynes** [comment]
S3 seems like it would be a good core storage adapter to have — @WoLfulus, do you think we could/should add this in?

**Comment by mvhirsch** [comment]
If you choose to do so, please do not forget to update the documentation :-)
https://docs.directus.io/extensions/storage-adapters.html#using-aws-s3

**Comment by mvhirsch** [comment]
Since `aws/aws-sdk-php` is included by default on api:v2-apache (and above) thanks to @WoLfulus, this issue looks like it can be safely closed. @benhaynes 

https://github.com/directus/docker/blob/13ee51ba89f301c6f1dc98bfc727f966ff2cb2b9/images/base/api/apache/Dockerfile#L29
