### ISSUE TITLE
Remove dev-packages from vendor/

### ISSUE THREAD

**Issue by mvhirsch** [directus/docker#38]
Hi,

a production environment won't need development packages, but they are installed on API (_/var/www/html/vendor/_).  Since dev-packages are only dead wood on production systems, they only add unnecessary filesize to docker images.

As far as I can see, this is done by the builder, but I don't know exactly how. I would like to help you guys with that, but there is no clear direction on how to build Docker images (especially the full process on getting them on Dockerhub). I would like to have a stable/continous and (hopefully?) automated building cycle for this.

Any way I can help you with that?

Greetings from Austria,
Michael

**Comment by WoLfulus** [comment]
Hi @mvhirsch 

This is getting carried from `app` releases itself. This repository doesn't install dependencies, we just grab releases from GitHub to build the final images.

Can you confirm this @rijkvanzanten ?

**Comment by rijkvanzanten** [comment]
I run `composer install -a` to create the package. I'll start adding the `--no-dev` flag too 👍

**Comment by mvhirsch** [comment]
Thank you @WoLfulus and @rijkvanzanten !

One quick tip, making the production-system even faster is using an optimized autoloader.
Just append `--optimize-autoloader`. This will take additional time, sure, but it results in a much faster php application!

https://getcomposer.org/doc/03-cli.md#install-i

**Comment by rijkvanzanten** [comment]
Thanks @mvhirsch! 

That's what the `-a` flag does 😄 

> --classmap-authoritative (-a): Autoload classes from the classmap only. Implicitly enables --optimize-autoloader.

**Comment by mvhirsch** [comment]
Ah, I just forgot about the "implicit" hint. Thank you! :-)
