### ISSUE TITLE
API configuration should support configuration through environment variables

### ISSUE THREAD

**Issue by WoLfulus** [directus/docker#4]
In docker, it's more common to get configurations through environment variables.

Maybe we can have have an additional `api_sample.php` ready for environment variables and docker inside the `api` repository so we can just move that file as the main one inside docker images (thus, avoiding files in the docker repository that can get out of sync with the `api` repository ones)

Related issues:

https://github.com/directus/directus-docker/issues/34

For reference, one I was playing with:

https://github.com/WoLfulus/directus-builder/blob/master/projects/api/api.php

**Comment by mvhirsch** [comment]
I think it already does this: https://github.com/directus/docker/blob/master/projects/api/api.php
At least, I'm able to use it with env variables like:

* DATABASE_HOST
* DATABASE_NAME
* ADMIN_EMAIL
* ADMIN_PASSWORD
* ...

But I can't find any description or documentation about this, sadly. Can we get this documented somewhere?

**Comment by WoLfulus** [comment]
Hi @mvhirsch!

It's on the repository `README.md` file

**Comment by WoLfulus** [comment]
This still needs discussion, but I'm closing this for now.
