### ISSUE TITLE
Improve DockerHub Documentation

### ISSUE THREAD

**Issue by jwlogemann** [directus/docker#40]
The dockerhub documentation for the project does not tell you the bare minimum you need to get the app up and running. Best case if you manage to guess something correctly is an app stuck at the login screen with an unknown username and password.
Please update the docs or remove the image from dockerhub.

**Comment by benhaynes** [comment]
Things move a bit slower in the OSS world (something to do with having no funding). Our developers have full-time jobs outside of this project and sometimes things get busy at work.

@WoLfulus (our Docker Lead) is busy at the moment, but will hopefully have time soon to address this. He has been working on a Docker refactor, and once complete that will replace all of these Docker instances.

**Comment by mvhirsch** [comment]
relates to #35

**Comment by mvhirsch** [comment]
also relates to #16

**Comment by WoLfulus** [comment]
I'm working on this together with #15 #16 and #82

**Comment by WoLfulus** [comment]
docker hub is getting updated automatically now. we're not adding a full guide over there but linking to a proper documentation as it uses the readme from this repository.
