### ISSUE TITLE
Custom docker image with S3 adapter issue

### ISSUE THREAD

**Issue by darrenzhu** [directus/docker#43]
## Version Info
  - Directus API version 2.0.14:

I'm trying to create a docker image based on the original directus-api image (from here: https://github.com/directus/docker/tree/master/projects), but with the aws-sdk-php installed. 

Without aws-sdk-php, I get an error when uploading files using the s3 adapter: `"[21-Jan-2019 18:52:03 UTC] PHP Fatal error: Uncaught Error: Class 'Aws\S3\S3Client' not found in /var/www/html/src/core/Directus/Filesystem/FilesystemFactory.php:59"`

I have the custom image created successfully with aws-sdk-php installed using composer. However, uploading files still fails. I don't receive the S3Client not found error anymore. But the request to the Files endpoint simply fails with a 500 error. There is no other log. I tried different combination of environment variables related to s3 storage settings but still no luck. Below are the only log entries I can see related to the upload error:
`172.16.8.69 - - [22/Jan/2019:04:00:08 +0000] "OPTIONS /_/files HTTP/1.1" 200 0 "http://direct-us-app-url/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36" "76.232.51.122"`

`2019/01/22 04:00:09 [warn] 214#214: *74 a client request body is buffered to a temporary file /var/tmp/nginx/client_body/0000000001, client: 172.16.8.69, server: _, request: "POST /_/files HTTP/1.1", host: "http://direct-us-api-url/", referrer: "http://direct-us-app-url/"`

`172.16.8.69 - - [22/Jan/2019:04:00:10 +0000] "POST /_/files HTTP/1.1" 500 57 "http://direct-us-app-url/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36" "76.232.51.122"`

Any help would be appreciated.

## Schema Dump, Logs, or Screenshots
Here is a screenshot of the environment variables I use. I'm hosting the Directus API and App in AWS ECR:
![tempsnip](https://user-images.githubusercontent.com/3039321/51511872-10e00d00-1dd1-11e9-87bd-bf33900ecb1f.png)

Below is the docker file with aws-sdk-php installed.
[Dockerfile.txt](https://github.com/directus/api/files/2781241/Dockerfile.txt)

**Comment by WoLfulus** [comment]
We are bundling the sdk by default in docker images now. I'm closing this because it's already stale and should be fixed already. Let me know if it persists
