### ISSUE TITLE
Saving item through API/app return CURL error 3: <url> malformed

### ISSUE THREAD

**Issue by GeospatialMax** [directus/docker#44]
Hi,

I am trying to write data to an item in a collection and no matter what I try, I always get a HTTP 500 response back with the following message:
`cURL error 3: <url> malformed (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)`

This happens through the App as well as directly through the API.

I did a bit of digging in the API code but couldn't really find where the issue is. I only found one place really where CURL is used which is in src/core/Directus/Application/CoreServicesProvider.php. But uncommenting the telemetry bit in there didn't make a difference.

Here is some information what I am running:

- API 2.1.0
- App 7.4.0

Both docker images built myself (as the versions on dockerhub are older).

The docker images are deployed to an _ECS Fargate cluster_ and are behind an application load balancer. The problem occurs independent of whether the docker container is accessed directly or through the load balancer.

Is there any other place where I can find logs than the standard docker logs which during runtime just consist of HTTP access logs?

Other than that, do you have an idea how this could be fixed?

**Comment by GeospatialMax** [comment]
@benhaynes , @WoLfulus :
I did some more digging, enabled the stacktrace to be returned in the error-handler and in the end it turned out to be an issue with a webhook function I defined in api.php. So it has nothing to do with the directus API / docker core code.

This issue can be closed therefore.

**Comment by benhaynes** [comment]
Thank you for following up @GeospatialMax!
