### ISSUE TITLE
Re-setup directus at every restart of the machine issue

### ISSUE THREAD

**Issue by AjayRawat001** [directus/docker#46]
I have followed this link to use Directus with docker-Hub
### https://hub.docker.com/r/getdirectus/directus

First time its work fine. But every restart of my machine it's not working
Error: 
Admins-iMac:~ **Admin$ docker run getdirectus/directus**
Running directus!
Enter password: ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
Warning: mysqli::__construct(): (HY000/2002): No such file or directory in /var/www/html/vendor/directus/migrations/lib/Ruckusing/Adapter/MySQL/MySQLBase.php on line 1296
Fatal error: Uncaught 
MySQLBase.php(1298) : 
Could not connect to the DB, check host / user / password
  thrown in /var/www/html/vendor/directus/migrations/lib/Ruckusing/Adapter/MySQL/MySQLBase.php on line 1298

**Comment by benhaynes** [comment]
I believe that is an outdated version of Directus — `getdirectus` was for v6 (and is no longer supported). All the newer Docker installs are in-work and should be updated soon by @WoLfulus

**Comment by AjayRawat001** [comment]
Okay Thanks
