### ISSUE TITLE
Docker revival

### ISSUE THREAD

**Issue by mvhirsch** [directus/docker#47]
Hello folks,

I really do love Directus :heart: 
In our environment we're using Docker all the time, which I love too!

I really want to use the Directus Docker images in near future, but at the moment, there aren't any updates on it, though. Any news so far?

I saw a promising rework done by @WoLfulus in https://github.com/directus/docker/tree/refactor/full but there is no progress (as far as I can see) for more than a month.
Is there something you guys and girls need help (by the community)?

I wish I can use the newest Directus features as of v7.2 to v7.5 :heart_eyes: 

Greets from Austria,
Michael

**Comment by WoLfulus** [comment]
Hi! The missing piece is being worked on api#930 which is proper support for configs. Then we're all set to get it autobuilding again.

**Comment by mvhirsch** [comment]
Sorry, I'm currently sparely on computer so I wanted to take a look at your improvements at https://github.com/directus/api/pull/930 but you just deleted it 10h ago :grinning: 

I think to follow up it is this one, correct? https://github.com/directus/api/pull/1048

**Comment by WoLfulus** [comment]
Yes! I squashed the commits and reopened it! :)

**Comment by mvhirsch** [comment]
As mentioned in https://github.com/directus/docker/issues/42#issuecomment-509306227 this should be solved this week :tada:

**Comment by vuhrmeister** [comment]
So can we expect new docker versions soon? I run into errors / bugs regularly with the old version. Bugs that are most likely all fixed during this long period. Would be super happy since we want to go to production very soon.

**Comment by dario30186** [comment]
I'm waiting for the docker images. Any news about the release date?
I saw that there is an unofficial docker image for directus updated to last version : https://hub.docker.com/r/ministryofprogramming/directus-app

but if we have to wait a few days, I prefer to use the official ones

**Comment by benhaynes** [comment]
@WoLfulus — you can post your updated timeline  here so the community knows when to expect it.

**Comment by dario30186** [comment]
Hi @WoLfulus , any news about the docker image update?

**Comment by WoLfulus** [comment]
Yes! We're almost there. You can check the refactor branch if you want :)

**Comment by WoLfulus** [comment]
Please check https://github.com/directus/docker/tree/develop
I'd love some feedback on the build process!

**Comment by mvhirsch** [comment]
Impressive @WoLfulus ! I really do like the process, I think it's good and will solve many use-cases :-)
I've tested your build steps, and do have some thoughts:

After reading the README it should be more clear, that most users will either use an "official image" (should be ranked on top for most common use cases) or build their own "base image". Describing how to build your own "core image" will lead to frustration in my opinion, since most users will just add something to your core image (like extensions or another php-configuration and so on). Building a core image is a rather rare use-case.

1. Please either provide nginx-support or do not mention it on building instructions like: https://github.com/directus/docker/tree/develop#build-a-nginx-image
2. Please provide _core_-images, so builds will be faster for any _base_-image build. (I think that's the plan?)

3. Can I select a _core_ image to build my _base_ image on? I wasn't able to to that, without having an exact same named core-image.
  
  ```
  # does not work, since base image cannot find a core image
  $> tusk core --namespace my-registry.com --kind apache --version latest
  $> tusk base --namespace my-registry.com --prefix directus --project app --kind apache --version 7.9.0
  ```
  ```
  # this works
  $> tusk core --namespace my-registry.com --prefix directus- --kind apache --version 7.9.0
  $> tusk base --namespace my-registry.com --prefix directus- --project app --kind apache --version 7.9.0
  ```
4. How is it supposed to add directus files at all? I couldn't get my test app image running, since apache tells me "404 Not Found" on "/". Inspecting the running container, I wasn't able to find any project files. I think I need to use the `ONBUILD` mechanism you described, but how? Where should I place my Dockerfile and project files?

**Comment by WoLfulus** [comment]
Hi! Thanks for the feedback!

I think I addressed most of what you said in the latest commit. Please take a look and let me know.

> Please provide core-images, so builds will be faster for any base-image build. (I think that's the plan?)

All images will be pushed to docker hub (dist, base and core).

> Can I select a core image to build my base image on? I wasn't able to to that, without having an exact same named core-image.

Base images in the current setup shares the same versioning model as core images (they are built and distributed together), this makes patches to core images propagate to new base images. It's by design, but without using the build scripts you can target a custom core image invoking `docker build` yourself passing `--build-arg CORE_IMAGE=...` arguments. Take tusk.yml as reference

> How is it supposed to add directus files at all? I couldn't get my test app image running, since apache tells me "404 Not Found" on "/". Inspecting the running container, I wasn't able to find any project files. I think I need to use the ONBUILD mechanism you described, but how? Where should I place my Dockerfile and project files?

I tried making it more clear in the readme. This docker repository won't be responsible for building the official/dist images, they will live in their respective repositories instead (which makes this easier if think about it)

They will extend `base` images (that has ONBUILD steps) to copy release contents to the image and publish them. We haven't released any base images yet because there are only `pre` releases, but as soon as I merge develop branch to master and create a release, base images should be available to do exactly what you want.

**Comment by mvhirsch** [comment]
Thank you very much! I just re-read the README (kudos for the new images :grinning: )

> They will extend base images (that has ONBUILD steps) to copy release contents to the image and publish them. We haven't released any base images yet because there are only pre releases, but as soon as I merge develop branch to master and create a release, base images should be available to do exactly what you want.

It does, of course this will help keep own changed versions of Directus small and clean.

I will close this issue, since you merged your refactoring-branch and build new Docker images (which I will check on next week!). :tada: 

Thank you for your hard work!

**Comment by WoLfulus** [comment]
Glad you liked it. :)

Base test images are published already. We'll start publishing dist images
soon.

Em qui, 15 de ago de 2019 11:33, Michael Hirschler <notifications@github.com>
escreveu:
