### ISSUE TITLE
CORS problem when trying to download files from uploads folder using axios/ajax

### ISSUE THREAD

**Issue by mfcanovas** [directus/docker#48]
I'm using axios to download files (is useful for customizing previews, zip files using JSZip, etc).

Axios send a preflight request (OPTIONS method) before sending the GET request. I'm getting a 405 Method Not Allowed error from nginx as OPTIONS method is not allowed by default.

As a workaround, I added these lines to nginx default.conf file:

```
location ~ /uploads/ {
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' '*';
        add_header 'Access-Control-Allow-Headers' '*';
        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Max-Age' 1728000;
            add_header 'Content-Type' 'text/plain; charset=utf-8';
            add_header 'Content-Length' 0;
	    add_header 'Access-Control-Allow-Origin' '*';
            add_header 'Access-Control-Allow-Methods' '*';
            add_header 'Access-Control-Allow-Headers' '*';
            return 204;
       }
}
```

It returns a 204 response for OPTIONS requests and adds CORS headers for all requests under uploads folder.

**Comment by mvhirsch** [comment]
Hi @mfcanovas,

by default CORS should be enabled: https://github.com/directus/docker/blob/master/projects/api/api.php#L121

What's your configuration on this and what is `axios` doing (GET, POST)?

**Comment by WoLfulus** [comment]
@mfcanovas did you make it work? I'm closing this for now as it seems stale. Let me know if it still persists on the latests images we published.
