### ISSUE TITLE
can't get the new docker images

### ISSUE THREAD

**Issue by PostPollux** [directus/docker#59]
Hi,
I just tried the new docker images and it seems I can't get them to work. I first tried it with my own docker-compose.yml but as I always got "Unknown error. Try again later." error message on the bottom of the loginpanel I decided to try it with the "simple.yaml" provided in the examples. But unfortunately it is exactly the same.

The logs from docker-compose are the following:

> api_1       | [2019-09-11 13:59:54] api[_].ERROR: Zend\Db\Adapter\Exception\InvalidQueryException: Statement could not be executed (42S02 - 1146 - Table 'directus.directus_settings' doesn't exist) in /var/www/vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php:244
api_1       | Stack trace:
api_1       | #0 /var/www/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(239): Zend\Db\Adapter\Driver\Pdo\Statement->execute
api_1       | #1 /var/www/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(209): Zend\Db\TableGateway\AbstractTableGateway->executeSelect
api_1       | #2 /var/www/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(196): Zend\Db\TableGateway\AbstractTableGateway->selectWith
api_1       | #3 /var/www/src/core/Directus/Application/CoreServicesProvider.php(1185): Zend\Db\TableGateway\AbstractTableGateway->select
api_1       | #4 /var/www/vendor/pimple/pimple/src/Pimple/Container.php(118): Directus\Application\CoreServicesProvider->Directus\Application\{closure}
api_1       | #5 /var/www/src/core/Directus/Container/Container.php(27): Pimple\Container->offsetGet
api_1       | #6 /var/www/src/helpers/settings.php(20): Directus\Container\Container->get
api_1       | #7 /var/www/src/helpers/settings.php(35): Directus\get_directus_settings
api_1       | #8 /var/www/src/helpers/settings.php(145): Directus\get_directus_setting
api_1       | #9 /var/www/src/core/Directus/Application/Http/Middleware/ProxyMiddleware.php(16): Directus\get_trusted_proxies
api_1       | #10 [internal function]: Directus\Application\Http\Middleware\ProxyMiddleware->__invoke
api_1       | #11 /var/www/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
api_1       | #12 [internal function]: Slim\DeferredCallable->__invoke
api_1       | #13 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
api_1       | #14 /var/www/vendor/akrabat/ip-address-middleware/src/IpAddress.php(113): Slim\App->Slim\{closure}
api_1       | #15 [internal function]: RKA\Middleware\IpAddress->__invoke
api_1       | #16 /var/www/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
api_1       | #17 [internal function]: Slim\DeferredCallable->__invoke
api_1       | #18 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
api_1       | #19 /var/www/src/core/Directus/Application/Http/Middleware/CorsMiddleware.php(66): Slim\App->Slim\{closure}
api_1       | #20 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke
api_1       | #21 /var/www/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
api_1       | #22 [internal function]: Slim\DeferredCallable->__invoke
api_1       | #23 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
api_1       | #24 /var/www/src/core/Directus/Application/Http/Middleware/ResponseCacheMiddleware.php(54): Slim\App->Slim\{closure}
api_1       | #25 [internal function]: Directus\Application\Http\Middleware\ResponseCacheMiddleware->__invoke
api_1       | #26 /var/www/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
api_1       | #27 [internal function]: Slim\DeferredCallable->__invoke
api_1       | #28 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
api_1       | #29 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}
api_1       | #30 /var/www/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack
api_1       | #31 /var/www/vendor/slim/slim/Slim/App.php(297): Slim\App->process
api_1       | #32 /var/www/src/core/Directus/Application/Application.php(161): Slim\App->run
api_1       | #33 /var/www/public/index.php(5): Directus\Application\Application->run [] []
api_1       | 172.23.0.4 - - [11/Sep/2019:17:59:54 +0000] "POST /_/auth/authenticate HTTP/1.1" 500 369 "http://app.localtest.me/" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
proxy_1     | nginx.1    | api.localtest.me 172.23.0.1 - - [11/Sep/2019:17:59:54 +0000] "POST /_/auth/authenticate HTTP/1.1" 500 133 "http://app.localtest.me/" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"

Any idea? Btw, what is the standard mail and password I would have to use with simple.yaml?

**Comment by WoLfulus** [comment]
you should setup the database manually. we won't be auto installing the database since its too risky to assume it should.

we're figuring out a way to display a setup dialog on app though

**Comment by PostPollux** [comment]
Wow that was fast, thanks!
Sorry for the noobish question, but how do I setup the database manually? And where do I get the schema.sql? Do you have any tutorial on that?

**Comment by WoLfulus** [comment]
schema.sql can be found on api repository under src folder. you should connect directly to the database (using mysql workbench or something) and run the script on the database.

**Comment by PostPollux** [comment]
Ok, thanks for the help. "simple.jaml" is working now. I can login.

But unfortunately I constantly get "Trouble processing request. Try again after refreshing the page." when I add a collection or a field or almost anything else. After refresh the things are there...
I guess this version is still buggy and not really ready for production. 
So I guess I have to stay with the previous version.

Maybe you can help:
The reason why I wanted to test the new version is the following:
I wanted to use a custom my-hooks.php for my api which i placed in a "hooks" folder next to my docker compose.
Then I mounted: ./hooks:/var/www/html/public/extensions/custom/hooks/
I started everything up. When I exec into the api container I can see that "my-hooks.php" is in the correct place.
BUT I can't connect to the api anymore. When I enter the address of my api in the browser it always displays exactly the content of "my-hooks.php". No matter what I put in this file. I tried the first example right at the top of https://docs.directus.io/extensions/hooks.html#creating-hooks, tried an empty array, tried just a comment... normally it should display something with "unauthorized"...
So I was thinking maybe it's the way the docker container handels it, let's try the new one.
Any idea how I could fix this problem in the old version (2.0.16)? Thanks in advance. And sorry for adding this problem to this issue. I can open a new one, if you want.

**Comment by WoLfulus** [comment]
I'm not that familiar with api code to be honest, try joining our slack and asking on #support channel. There are more people that can help there :)

I'm closing this one ok?

**Comment by glenselle** [comment]
Could I submit a PR to the README of this repo that would include a small section showing how to run the compose file and the `schema.sql` file mentioned here? I feel like this is an important detail that's not currently documented which would make it much easier for people to get started running directus locally. Something like the following:

## Getting Started
To get started with directus via docker compose, download one of the example compose files in `/examples`. Then `cd` into the same directory and run docker compose:

```bash
$ docker-compose -f simple.yaml up -d
```
Once everything is up, download a copy of `schema.sql` from the `/src` directory of the [directus/api](https://github.com/directus/api) repo, and in the same directory as `schema.sql` run:
```bash
$ docker run -it --network directus_default -v $(pwd):/setup mysql sh -c 'exec mysql -hdirectus_database_1 -uroot -p directus < /setup/schema.sql'
```
**If you have altered any values in the docker compose YAML file, update this command.** Make sure the network name (`directus_default`), hostname (`directus_database_1`) and database name (`directus`) are correct. You will be prompted for the password of the user specified with `-u`. 

If successful, the container will exit without any further output. Now you should be able to navigate to the directus app URI and login with `admin@example.com` and `password`. 

Congrats! You've got directus running!

**Comment by glenselle** [comment]
Just noticed the #docker channel in Slack had another option for obtaining and running the `schema.sql` file which also works, though it does include the password in the command: 

```bash
$ curl https://raw.githubusercontent.com/directus/api/master/src/schema.sql | docker-compose exec -T database sh -c 'mysql -u directus -D directus -pdirectus
```
taken from: https://rangerstudio.slack.com/archives/C0GQ5406T/p1568117967077200

**Comment by glenselle** [comment]
I'm willing to submit a PR to add a "Getting Started" section with either of these two methods documented. Would one of these options be preferable over the other?

**Comment by WoLfulus** [comment]
We'd love that, but I'm planning on keeping the readme clean and just pointing to an external (proper) documentation page for docker.

Also, this doesn't cover everything though (for example we had some cases in which schema wasn't reliably updated from time to time), and I prefer running the migrations instead of importing a dump.

In resume, we're still trying to figure out a proper way to setup the database :)

I'd love some input in #docker channel though.

**Comment by WoLfulus** [comment]
As an update, I submitted a PR to api and I'm working on an alternative way to do it right now in which won't be risky, will support current workflows (composer, kubernetes, helm), and allows us to get the database up in a more convenient way :)
