### ISSUE TITLE
examples simple issue

### ISSUE THREAD

**Issue by EsajeeSolutions** [directus/docker#61]
i have followed the guide as in examples/simple one, but installer is giving error 

docker-compose run installer install --email your@email.com --password somepass

![image](https://user-images.githubusercontent.com/6302184/64938401-31d10300-d877-11e9-95ee-76434521f5eb.png)

and on frontend app is giving error, and on which it says no database table for directus settings

i have seen that the latest code is fixed in 0.0.14 version, but we are using api/v2-apache which is reason

any help

**Comment by WoLfulus** [comment]
It's not published yet. The latest version published uses base 0.0.14, I'm waiting for the next release to happen.
