### ISSUE TITLE
docker hub doesn't have the latest image

### ISSUE THREAD

**Issue by akadoya** [directus/docker#62]
Hi,
I am going through the sample and found that the latest changes are not reflecting to the images on Docker Hub.
https://hub.docker.com/r/directus/api/tags

latest master branch has this sample and steps
https://github.com/directus/docker/tree/master/examples/simple
but this is depending on the entrypoint change you made a few days ago and it is not in the latest image in DockerHub, apparently.

To be clear, docker-compose run end up kicking OS-build in install command instead of the install function for api-entrypoint script.
```
root@0bd840b0a0d0:/var/www/public# which install
/usr/bin/install
root@0bd840b0a0d0:/var/www/public# install --email your@email.com --password somepass
install: unrecognized option '--email'
```

Is there any chance to sync up the latest updates with Docker Hub?

**Comment by TonyEight** [comment]
Agree with the analysis. Docker Hub images seem to be outdated.

**Comment by WoLfulus** [comment]
This was fixed some time ago, but since we haven't had a release until today, the images weren't updated (mentioned in #61)

We're already in the process of building and publishing the images for the latest version
