### ISSUE TITLE
Directus database installation

### ISSUE THREAD

**Issue by a2dx** [directus/docker#63]
Hello,

i am trying to install directus with the given example for docker.
https://github.com/directus/docker/blob/master/examples/simple/docker-compose.yaml

At first i execute:
docker-compose up -d

and then for the database installation i execute:
docker-compose run installer install --email your@email.com --password somepass

After the following message appears:
-------------------------------------------------------------

  Directus installation completed, you can now
  login with the following credentials:

      Email: your@email.com
   Password: 

-------------------------------------------------------------

Okay, no password is displayed but the user was registered.

I also looked into the mysql database whether the user is really there, and he is. So everythink should work.

When i try to login at http://app.localtest.me/#/login with the credentials: --email your@email.com --password somepass

it says wrong password. What am i doing wrong, why it is not working.
Could anybody please help me?

Thank you in advance.

Best regards

**Comment by WoLfulus** [comment]
I'll try to reproduce this. Please confirm what images you are using

**Comment by akadoya** [comment]
I have the same issue with the latest image.
```
     Container                  Repository                Tag        Image Id      Size
-----------------------------------------------------------------------------------------
directus_api_1         docker.io/directus/api          v2-apache   86e830fda206   667 MB
directus_app_1         docker.io/directus/app          v7-node     072325c15b3c   456 MB
directus_installer_1   docker.io/directus/api          v2-apache   86e830fda206   667 MB
directus_mysql_1       docker.io/mysql                 5.7         383867b75fd2   356 MB
directus_proxy_1       docker.io/jwilder/nginx-proxy   alpine      730317336993   51.8 MB
```

When running the install command, the installer gets stuck somewhere and unless I send Ctrl+C signal once, it does not exit.

**Comment by edenprojectde** [comment]
Would love to get this working as i am not that knowledgable of docker, the examples would be really nice to use to work on client pages :')

**Comment by WoLfulus** [comment]
@edenprojectde is it still giving problems? the examples already covers some simple cases (that can be used to work locally)

also the problem in question should be already fixed in the latest images

**Comment by edenprojectde** [comment]
I pulled it today, and have the same Problem as described,
running the examples and then trying to set up the account gives me this result on the account creation command:
![Screenshot_20191023_002056](https://user-images.githubusercontent.com/6115966/67339191-fe932b00-f52a-11e9-83c6-6059123ea344.png)
And i cant log in in the app.

**Comment by akadoya** [comment]
doesn't reproduce with the latest image for me.
docker-compose pull
docker-compose up -d --force-recreate --build
will force to pull the latest image.

you can also verify that you have the latest image by running docker pull directus/api:latest and comparing the digest for the image you have for directus/api:v2-apache

**Comment by edenprojectde** [comment]
That didnt do the trick for me,
i did 
```git pull
docker-compose pull
docker-compose up -d --force-recreate --build
```

Everything went fine. But trying the account creation did the same thing again. It stuck at `Starting simple_mysql_1 ... done` and then i need to CTRL+C so it continues (Which probably means he is failing installing the database correctly?).

![Screenshot_20191026_133456](https://user-images.githubusercontent.com/6115966/67618895-6b414a80-f7f5-11e9-89d2-6136dfcb4da9.png)

**Comment by edenprojectde** [comment]
```ben@EdenTheFourthVII:~/Projekte/OS/directus/docker/examples/simple$ docker pull directus/api:latest
latest: Pulling from directus/api
Digest: sha256:09bd06d9c8a196599ccf18a813162b9815b4283b8ed955bfd98a2119805aec79
Status: Image is up to date for directus/api:latest
```

**Comment by hedwiggggg** [comment]
I got the same problem as edenprojectde.

**Comment by WoLfulus** [comment]
This should be fixed by now, please let me know if there are any further issues, and refer to `examples` on how to run the installer.

https://github.com/directus/docker/tree/master/examples/simple
