### ISSUE TITLE
DIRECTUS_AUTH_SECRETKEY is required

### ISSUE THREAD

**Issue by LukasNavickas** [directus/docker#64]
I'm trying to launch directus API on docker container, but I'm getting the following error after installing the newest API version 2.6.0:
![image](https://user-images.githubusercontent.com/13028072/65617978-db25a080-dfbd-11e9-8b29-33f92358e7e0.png)
If I provide a random string as DIRECTUS_AUTH_SECRETKEY, I'm getting another issue:
![image](https://user-images.githubusercontent.com/13028072/65618093-07d9b800-dfbe-11e9-9333-8df0ae1533e6.png)
Any ideas?

**Comment by WoLfulus** [comment]
what is the issue in the second case? seems normal to me

**Comment by imaneRachdi** [comment]
![image](https://user-images.githubusercontent.com/19638944/65661472-0944c800-e032-11e9-843f-d8f22b5b2359.png)

in the second case, failed to connect to the database . We have tried  also  image v2.5.0, but we got the same error .

**Comment by WoLfulus** [comment]
This doesn't seem like a directus problem but a setup one. 

Please review: 
- database-related environment variables
- links between the containers 
- network interfaces inside the compose file
- if api container can ping database container
 
If it persists, please share the docker-compose file and confirm docker version and docker-compose version used.

**Comment by WoLfulus** [comment]
updates on this one?

**Comment by benhaynes** [comment]
@LukasNavickas @imaneRachdi — let us know if you're able to resolve this problem given the new information. Thanks!

**Comment by imaneRachdi** [comment]
Hey, sorry for the delated answer .

Unfortanutely, we couldn't resolve the problem, so we had to install directus locally with phpmyadmin .

docker version : Docker version 19.03.1, build 74b1e89 
docker-compose version : docker-compose version 1.24.1, build 4667896b
here is the docker-compose we are using : 

version: "3"

services:

  
  database:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: "somedb"
      MYSQL_ROOT_PASSWORD: "rootpassword"
      MYSQL_USER: "someusername"
      MYSQL_PASSWORD: "somepassword"
    ports:
      - 3306:3306

  
  api:
    image: directus/api:latest
    environment:
      DATABASE_HOST: database
      DATABASE_NAME: "somedb"
      DATABASE_USERNAME: "someusername"
      DATABASE_PASSWORD: "somepassword"
      ADMIN_EMAIL: "admin@localhost.com"
      ADMIN_PASSWORD: "directusrocks"
    ports:
      - 7000:80

 
  app:
    image: directus/app:latest
    environment:
      API_ENDPOINT: "API; http://localhost:7000/_/"
    ports:
      - 8000:80

**Comment by WoLfulus** [comment]
@imaneRachdi hi!

Seems like networks and/or links are missing on your compose file, that is why your containers are not seeing each other (db connection error).

We have some examples on this repository under `examples` folder, it should give you an idea of a full setup.

As a reference: https://docs.docker.com/compose/compose-file/#links

I'm closing this one. Let me know if you can get it working ;)

**Comment by WoLfulus** [comment]
See examples for proper setup. `DIRECTUS_AUTH_SECRETKEY` can be anything, it just needs to be set in order to keep your installation secure.
