### ISSUE TITLE
Api logfile should be bound to stderr

### ISSUE THREAD

**Issue by lrkwz** [directus/docker#7]
In my opinion you hould configure 

* apache log bound to stdout (quite useless in my opinion)
* application error log bound to stderr

**Comment by WoLfulus** [comment]
Apache was dropped for nginx... 

If i'm not mistaken It's already set to stdout/stderr now, but I'll double check that...

:)

**Comment by lrkwz** [comment]
You re right latest image has nginx on board but still `/var/www/html/logs` contains a log file which you cannot see using `docker-compose logs -f`.

`docker-compose exec directus-api tail -f "/var/www/html/logs/error.2018-11-16.log"` is still the only way.

**Comment by WoLfulus** [comment]
Awesome! I'll take a look!

**Comment by lrkwz** [comment]
In your `/etc/php7/php-fpm.conf`

    error_log = /proc/self/fd/2

is already configure.

BUT ...

https://github.com/directus/api/blob/master/src/core/Directus/Application/CoreServicesProvider.php#L59 tells us you are using Monolog|Logger wich is configured to write in a file and probably can be configured to write into `/proc/self/fd/2` (see https://github.com/directus/api/blob/master/src/core/Directus/Application/CoreServicesProvider.php#L111)

**Comment by mvhirsch** [comment]
Monolog uses Handlers for this. The `StreamHandler` is already used in Directus, but setting it to a file.
Instead of doing so, the `StreamHandler` is capable of writing to any stream (like STDOUT).

```php
$handler = new StreamHandler('php://stdout', $level);
$logger->pushHandler($handler);
```

----

Sidenote: after a quick look at the code in `CoreServicesProvider::getLogger()`, it looks like much more complicated then it should. Monolog is capable of logging to "level N + above". For example setting the default level of the `StreamHandler` to 'INFO' will log INFO, WARNING, ... but DEBUG.

There is no need to create various StreamHandler per level.

**Comment by WoLfulus** [comment]
@WellingGuzman can we work out a way to configure (api.php) the logger so we can forward everything to the stdout/stderr instead of the default Writer that uses dated files in logs folder?

Its been a real pain to debug stuff inside docker without logs being forwarded to the terminal

**Comment by WellingGuzman** [comment]
Sure, I think the quickest solution will be to move the custom path format to the config, so it allows to set the path to `php://stdout` and ignore the file logging to `logs` directory.

**Comment by WoLfulus** [comment]
@WellingGuzman have this landed in api already?

**Comment by mebenhoehta** [comment]
We would be very interested in this. Please let me know if this is being worked on and if not we might start work on.

**Comment by benhaynes** [comment]
Thanks @mebenhoehta — any thoughts on this @WoLfulus ?

**Comment by vacri** [comment]
Hi folks - has there been any movement on this? I'm struggling with finding a working hack to push the logs into stdout for docker to pick up.

**Comment by WoLfulus** [comment]
this should be fixed on the refactor. i'm planning on pushing new images this week

**Comment by nicam** [comment]
Thanks :)

If someone else is looking into how to configure this:

`    'settings' => [
        'logger' => [
            'path' => 'php://stdout',
        ],
    ],`
