### ISSUE TITLE
Seed uploads folder when mounting to host

### ISSUE THREAD

**Issue by WoLfulus** [directus/docker#76]
Entrypoint should check if uploads folder is empty and do the proper seed of the directory (.htaccess and stuff) in case it is.

**Comment by zfalen** [comment]
I noticed this today during setup _(and saw a conversation about it in the slack support channel)_ can confirm that as long as that folder is volumed, even if I manually seed it with the right files from https://github.com/directus/api/tree/develop/public/uploads and `chmod -R 755` the whole public directory, I get permissions errors when uploading files from the GUI / App

**Comment by WoLfulus** [comment]
I'll take a look as soon as possible. :)

Em qui, 31 de out de 2019 19:20, zfalen <notifications@github.com> escreveu:

**Comment by WoLfulus** [comment]
Solved in #9dcff9f5

**Comment by moekify** [comment]
@WoLfulus, you made these changes 20 days ago, however latest image on dockerhub is from 23 days ago. Assuming, these are not in the current image on dockerhub. 

When are the images usually updated?

**Comment by benhaynes** [comment]
@WoLfulus 🔔
