### ISSUE TITLE
imagick not available on api image

### ISSUE THREAD

**Issue by inta** [directus/docker#80]
Hey people, it took me quite some time to realize that imagick is missing inside the official docker images.

I think it would be nice to include everything required for the full Directus experience. What do you think about it? Should not be that much work to do, but would obviously increase the image size.

**Comment by benhaynes** [comment]
Absolutely. It's easy to include that, and makes the experience better. @WoLfulus 🔔

**Comment by inta** [comment]
Ok, I have created a pull request (#81) adding imagick to the core apache image. I hope that is correct, the image build finishes without errors, but I did not figure out how to build the images on top of the base ones (those available on docker hub as "directus/api").
