### ISSUE TITLE
Info on docker hub is not that helpful

### ISSUE THREAD

**Issue by inta** [directus/docker#82]
The info on docker hub is not very helpful. For the [API](https://hub.docker.com/r/directus/api) and [App](https://hub.docker.com/r/directus/app) it seems to be just the README.md of the github repo and [Base](https://hub.docker.com/r/directus/base), [Core](https://hub.docker.com/r/directus/core) and [Suite](https://hub.docker.com/r/directus/directus) info is (almost) empty.

I know the images are still in an early stage, but if you want people to test and use them there should be at least some basic info.

What I would expect on those page is:
- What different tags are there and what do they mean? What is the yolo tag meant for?
- How to configure the images?
- Which paths should/could be mounted as volumes?
- Which environment variables are supported? What are their defaults?

If there are images which are (currently) unmaintained, that should be made clear to the user. The Suite image comes to my mind (because it is outdated).

**Comment by mvhirsch** [comment]
Relates to #40

**Comment by benhaynes** [comment]
Hey @WoLfulus — any thoughts on timing for getting all this organized? I know we want to push out the v8 Docker instances first, but after that we should use this ticket as a reference for cleaning up all the different Docker repos (on DockerHub) as well as READMEs and Docs. ❤️

**Comment by WoLfulus** [comment]
I'm working on this together with #15 #16 and #40

**Comment by jooola** [comment]
@WoLfulus Just an idea to keep things in a single place: https://github.com/peter-evans/dockerhub-description

**Comment by WoLfulus** [comment]
that is nice! I'll use that one as a base

**Comment by WoLfulus** [comment]
docker hub is getting updated automatically now.
