### ISSUE TITLE
Automate Docker images

### ISSUE THREAD

**Issue by mvhirsch** [directus/docker#83]
Hey there, since there are so many new releases (formerly v8) coming, I think it's time to automate the docker images build process using Continous Delivery.

This will help automatically building new images after release either APP or API, so anyone can start using the latest Directus images right away.

What do you need for this? Can I help you?
Building own Directus images is still a challenge, streamlining this process will help the project _and_ the community.

Greets from Austria,
Michael

**Comment by remoblaser** [comment]
I'd be open to help as well :)

**Comment by WoLfulus** [comment]
It's done already, I should just enable it inside travis pipeline - I'll be testing this later today.

Also, the team decided to get rid of `app` and `api` images, so we'll stick to just `directus/directus` one now.

**Comment by WoLfulus** [comment]
This is applied already. We'll start creating releases here as soon as we make new `directus/directus` releases (that's how it's triggered).
