### ISSUE TITLE
How to deploy with docker swarm?

### ISSUE THREAD

**Issue by pwFoo** [directus/docker#85]
I try to deploy directus with docker swarm and tried some compose I found.
I can reach the api und see the admin backend login page, but connection to api fails.

directus database isn't installed. So it looks like directus/api need an installer? but how to execute install of directus?

**Comment by WoLfulus** [comment]
@pwFoo check examples's readme files. let me know if it works for you

**Comment by pwFoo** [comment]
Example image:
```
  directus:
    image: directus/directus:v8-apache
```

But I tried it with:
```
image: directus/api
[...]
image: directus/app
```

Found how to install the database from inside of the container. 
```
export DIRECTUS_INSTALL_TITLE=test
export DIRECTUS_INSTALL_EMAIL=me@example.com
# password is needed, fails without!
export DIRECTUS_INSTALL_PASSWORD=password

/usr/local/bin/api-entrypoint install
```
So it's installed and should be ready to login.

Connection between containers (app, api and mysql) works fine. Also api to mysql and app to api, but app still says "could not reach api"...?

**Comment by pwFoo** [comment]
Added "/_/" to api path and now it works, but should be better documented and added examples how to install.

**Comment by WoLfulus** [comment]
Separate api and app are not supported anymore in v8 and we'll not maintain those anymore. They are bundled together in `directus/directus` image now.

The installation process (as well as the steps needed to get the database installed), at least for now is documented on examples and their respective readmes.

> Existing ENV VARS and configuration possibilities.

These are supposed to be 1:1 with configuration files in which each level is separated by `_`, prefixed with `DIRECTUS_`

> trigger install from inside of the container

This is for now documented in readme files of examples. We'll move to a proper documentation page later.

> why is password needed for successful installation, I read it's optional?

Not sure if I got this one. But if you mean the secrets, it's to avoid having same secret for different installations, allowing people to generate JWT payloads and logging into other people's instances and yet avoiding problems with login when scaling to multiple containers.

**Comment by WoLfulus** [comment]
@pwFoo please let me know if those examples works for you.

**Comment by pwFoo** [comment]
Got it running with the directus image. Have to take a closer look into config options.

**Comment by WoLfulus** [comment]
I'll write a proper documentation this week :)
