### ISSUE TITLE
Docker api testing image

### ISSUE THREAD

**Issue by jooola** [directus/docker#87]
I started to import a project for gatsby at https://github.com/directus/gatsby-source, my main concern now is to test this tool using CI.
I found 2 ways of doing this:
- testing directly against the demo instance, but this add an external party to the tests and the stability might be impacted by any changes made up there. 
- Creating a test API docker image, that can be run in CI as a service, and working against this with a static set of data. This tool could also be used by the API repository to make E2E testing in the future.

Second option seems the best. So I would like to know if I can propose a test image that could be pushed to docker hub and that I can use for this purpose. @WoLfulus Tell me if this docker image should be moved away from this repo, and any other concerns you may have about this?.

**Comment by WoLfulus** [comment]
Just to make sure I understand: a test image would be an image with builtin data?

**Comment by jooola** [comment]
@WoLfulus Yeah that's the idea, and now that you say that, the existing image could provide these data ? This would be awesome !

**Comment by jooola** [comment]
Ok, I just had a new way of doing this sorry to bother. If I create 2 services (directus and mysql) and migrate the database myself I can add any set of data I like.

**Comment by WoLfulus** [comment]
You can also put a .sql dump mounted to mysql initialization container too. It will seed your database for you and you won't need to run the migration as an additional step.

BTW, I thought about this a while ago, even for testing if images are working properly inside travis (before pushing them), but I think this would be easier after we migrate to laravel (we'll be able to use sqlite as the database adapter, making it easier to embed a database in there)
