### ISSUE TITLE
Docker: directus/directus:latest does not exist as an image

### ISSUE THREAD

**Issue by damusix** [directus/docker#98]
# Bug Report

Trying to pull latest directus via kitematic and it does not have the `latest` tag

## Steps to Reproduce

download latest docker image `docker pull directus/directus:latest`
```
Error response from daemon: manifest for directus/directus:latest not found: manifest unknown: manifest unknown
```

## Expected Behavior
Should pull the latest directus image

**Comment by WoLfulus** [comment]
We don't push latest image. You should specify which image you want to use, for example "v8-apache"
